name: whatsmeow-mqtt-bridge

services:
  mqtt:
    image: eclipse-mosquitto:2@sha256:6f8d8a947c506f8a2290ec65cd4bd2bc7cb4d43fb5f6271f861cb013e2ef9797
    restart: unless-stopped
    volumes:
      - ./deploy/mosquitto.conf:/mosquitto/config/mosquitto.conf:ro

  bridge:
    depends_on:
      - mqtt
    environment:
      MQTT_URL: mqtt://mqtt:1883
